@company.api_HostAddress = http://localhost:5219


###

### Get list of employees
GET {{company.api_HostAddress}}/api/employees
Accept: application/json

### Get single employee by id 
GET {{company.api_HostAddress}}/api/employees/1
Accept: application/json

###

POST {{company.api_HostAddress}}/api/login
Content-Type: application/json
{
  "username": "admin",
  "password": "admin123"
}
